// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcmVDIvqnjHSaeTXuZEJtpWOBvdhpTdAI',
    appId: '1:538265150885:web:a2cbbb9e809bd8bc06b44c',
    messagingSenderId: '538265150885',
    projectId: 'ecommerce-5c326',
    authDomain: 'ecommerce-5c326.firebaseapp.com',
    storageBucket: 'ecommerce-5c326.firebasestorage.app',
    measurementId: 'G-TZSSTVX4N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4h7DKaXIi0ADxs5uxEmKqyTuKVmP42uc',
    appId: '1:538265150885:android:889f7e277627a5ce06b44c',
    messagingSenderId: '538265150885',
    projectId: 'ecommerce-5c326',
    storageBucket: 'ecommerce-5c326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpNnaqnJnupeuYpe3JH_m8WWgmkOpMf0',
    appId: '1:538265150885:ios:61bf49b593c4ecd406b44c',
    messagingSenderId: '538265150885',
    projectId: 'ecommerce-5c326',
    storageBucket: 'ecommerce-5c326.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXpNnaqnJnupeuYpe3JH_m8WWgmkOpMf0',
    appId: '1:538265150885:ios:61bf49b593c4ecd406b44c',
    messagingSenderId: '538265150885',
    projectId: 'ecommerce-5c326',
    storageBucket: 'ecommerce-5c326.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcmVDIvqnjHSaeTXuZEJtpWOBvdhpTdAI',
    appId: '1:538265150885:web:4ea3e28ab11bfcc506b44c',
    messagingSenderId: '538265150885',
    projectId: 'ecommerce-5c326',
    authDomain: 'ecommerce-5c326.firebaseapp.com',
    storageBucket: 'ecommerce-5c326.firebasestorage.app',
    measurementId: 'G-G36X5J3Q6P',
  );
}
